package br.com.unip.cardapio.exception

enum class ECodigoErro {

    ERRO_INESPERADO("000"),
    TOKEN_EXPIRADO("001"),
    TOKEN_INVALIDO("002"),
    CONEXAO_RECUSADA("003"),
    ACESSO_NEGADO("004"),
    CAMPO_OBRIGATORIO("005"),
    PARAMETRO_INVALIDO("006"),
    CAMPO_DEVE_SER_NUMERICO("007"),
    TITULO_CARDAPIO_OBRIGATORIO("008"),
    FORMATO_DATA_INVALIDO("009"),
    PRODUTO_NAO_ENCONTRADO("010"),
    ID_PRODUTO_OBRIGATORIO("011"),
    USUARIO_NAO_POSSUI_CADASTRO("012"),
    CARDAPIO_NAO_ENCONTRADO("013"),
    PRODUTO_NAO_ESTA_NO_CARDAPIO("014"),
    CATEGORIA_NAO_ENCONTRADA("015"),
    TITULO_CATEGORIA_OBRIGATORIO("016"),
    CAMPO_VALOR_DEVE_SER_NUMERICO("017"),
    CAMPO_VALOR_OBRIGATORIO("018"),
    CAMPO_DESCRICAO_OBRIGATORIO("019"),
    CAMPO_NOME_OBRIGATORIO("020"),
    CAMPO_ESTOQUE_NAO_PODE_SER_NEGATIVO("021"),
    SUBCATEGORIA_NAO_ENCONTRADA("022"),
    POSSUI_ITENS_DO_CARDAPIO_EM_CARRINHOS("023"),
    LIMITE_DE_CARDAPIOS_ATINGIDO("024"),

    POSSUI_CARDAPIO_CADASTRADO("030");

    val codigo: String

    constructor(codigo: String) {
        this.codigo = codigo
    }
}